scratch-org-def: config/project-scratch-def.json
  assign-permset: true
  permset-name: LoggerPermissions
  permset-name: CodeClicksKafka
  run-apex-tests: true
  delete-scratch-org: false
  show-scratch-org-url: true